# Generated by Django 4.0.5 on 2022-06-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monk',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
