# Generated by Django 4.0.5 on 2022-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_monk_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monk',
            name='title',
            field=models.CharField(choices=[('Sir', 'Sir'), ('Madam', 'Madam'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Master', 'Master'), ('Mistress', 'Mistress'), ('Bishop', 'Bishop')], default='Brother', max_length=30, verbose_name='Title of address'),
        ),
    ]
