# Generated by Django 4.0.5 on 2022-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_monk_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='main/media')),
            ],
        ),
    ]
