# Generated by Django 4.0.5 on 2022-06-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pictura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictura',
            name='image',
            field=models.ImageField(upload_to='monastic_blog/media/img/'),
        ),
    ]
