# Generated by Django 4.0.5 on 2022-06-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pictura_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='monk',
            name='userpic',
            field=models.ImageField(default='media/img/undefined_monk.jpg', upload_to='media/img', verbose_name='Userpic'),
        ),
        migrations.AlterField(
            model_name='pictura',
            name='image',
            field=models.ImageField(upload_to='media/img/'),
        ),
    ]
