# Generated by Django 4.0.5 on 2022-06-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_monk_userpic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictura',
        ),
    ]
