# Generated by Django 4.0.5 on 2022-06-14 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayers', '0002_prayer_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='amens',
            field=models.ManyToManyField(related_name='prayers', to=settings.AUTH_USER_MODEL),
        ),
    ]
