# Generated by Django 4.0.5 on 2022-06-15 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayers', '0003_prayer_amens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='amens',
            field=models.ManyToManyField(related_name='amenned_prayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Incognito', max_length=200)),
                ('text', models.TextField()),
                ('publicatio', models.DateTimeField(blank=True, null=True)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prayers.prayer')),
            ],
        ),
    ]
